<?php
return [
	'dir' => [
		'purchased_invoices' => 'uploads/docs/purchased_invoices/',

		'issue_vaucher' => 'uploads/issuevaucher/',
		'diamond_invoice' => 'uploads/diamondinvoice/',

		'invoice_attachment' => 'uploads/paymentinvoice',

		'paid_invoice_attachment' => 'uploads/paid_invoice',

		'return_to_vendor_voucher' => 'uploads/return_to_vendor_receipts/',

		'diamond_invoice_attachment' => 'uploads/invoice_attachment',
		'product_list_img' => '/html/DML-Internal-Software-2.0/public/',
		'product_list_img_def' => '/html/DML-Internal-Software-2.0/public/img/',
		'website_url_for_product_image' => 'http://203.112.144.7/media/catalog/product/',
		'website_url_for_product_image_curl' => 'http://10.22.40.7/media/catalog/product/',

		'return_to_vendor_receipts' => 'uploads/return_to_vendor_receipts/',
		'qrcode_images' => 'img/product_qrcodes/',
		'product_image_path' => 'uploads/img',
		// etc
	],
	'Discount_type' =>
	[
		//14k
		'approval_less25' => 'discount_approval_less_25',
		'approval_25tolakhs' => 'discount_approval_25_to_lakhs',
		'approval_abovelakhs' => 'discount_approval_above_lakhs',
		'deposit_less25' => 'discount_deposit_less_25',
		'deposit_25tolakhs' => 'discount_deposit_25_to_lakhs',
		'deposit_abovelakhs' => 'discount_deposit_above_lakhs',
		'invoice_less25' => 'discount_invoice_less_25',
		'invoice_25tolakhs' => 'discount_invoice_25_to_lakhs',
		'invoice_abovelakhs' => 'discount_invoice_above_lakhs',

		//18k
		'approval_less25_18K' => 'discount_approval_less_25_18k',
		'approval_25tolakhs_18K' => 'discount_approval_25_100k_18k',
		'approval_abovelakhs_18K' => 'discount_approval_gt_100k_18k',
		'deposit_less25_18K' => 'discount_deposit_less_25_18k',
		'deposit_25tolakhs_18K' => 'discount_deposit_25_100k_18k',
		'deposit_abovelakhs_18K' => 'discount_deposit_gt_100k_18k',
		'invoice_less25_18K' => 'discount_invoice_less_25_18k',
		'invoice_25tolakhs_18K' => 'discount_invoice_25_100k_18k',
		'invoice_abovelakhs_18K' => 'discount_invoice_gt_100k_18k',
	],
	'Metal_Quality' => [
		'14K Yellow Gold' => '14K Yellow Gold',
		'14K White Gold' => '14K White Gold',
		'14K Rose Gold' => '14K Rose Gold',
		'18K Yellow Gold' => '18K Yellow Gold',
		'18K White Gold' => '18K White Gold',
		'18K Rose Gold' => '18K Rose Gold',
		'18K Two Tone' => '18K Two Tone',
		'14K Two Tone' => '14K Two Tone',
		'Platinum(950)' => 'Platinum(950)',
		'14K Three Tone' => '14K Three Tone',
		'18K Three Tone' => '18K Three Tone',
	],
	'message' => [
		/* ManagechargesController */
		'vendor_charges_add_success' => 'Record added successfully',
		'vendor_charges_update_success' => 'Record updated successfully',
		/* ManagechargesController */

		/* MetalratesController */
		'vendor_metal_rates_add_success' => 'Record added successfully',
		'vendor_metal_rates_update_success' => 'Record updated successfully',
		/* MetalratesController */

		/* DiamondTypeController */
		'vendor_DiamondType_add_success' => 'Diamond Type created successfully',
		'vendor_DiamondType_update_success' => 'Diamond Type updated successfully',
		/* DiamondTypeController */

		/* ProductTypeController */
		'vendor_ProductType_add_success' => 'Product Type created successfully',
		'vendor_ProductType_update_success' => 'Product Type updated successfully',
		/* ProductTypeController */

		/* ProfileController */
		'vendor_current_password_error' => 'Your current password does not matches with the password you provided. Please try again.',
		'vendor_new_password_error' => 'New Password cannot be same as your current password. Please choose a different password.',
		'vendor_new_password_success' => 'Password changed successfully !',
		/* ProfileController */

		/* PaymentTypeController */
		'Payment_Type_add_success' => 'Payment Header Created Successfully',
		'Payment_Type_update_success' => 'Payment Header Updated Successfully',
		'Payment_Type_delete_success' => 'Payment Header Deleted Successfully',
		/* PaymentTypeController */

		/* PaymentController */
		'payment_adv_payment_created_successfully' => 'Advance payment created successfully',
		'payment_customer_not_selected' => 'Please select customer',
		'payment_customer_remark_required' => 'Remarks is required',
		'Payment_add_success' => 'Payment created successfully',
		'Payment_update_success' => 'Payment updated successfully',
		'Payment_Approved_success ' => 'Payment Approved successfully',
		'Payment_Decline_success ' => 'Payment Decline successfully',
		'Allredy_Approved ' => 'This Transaction Allredy Approved',
		'Allredy_Decline' => 'This Transaction Allredy Decline',
		'Payment_delete_success ' => 'Payment Information deleted successfully',

		/* SettingController */
		'settings_saved' => 'Settings Saved',
		'settings_error' => 'Issue Voucher No is already is exist , Please change the series or prefix from Settings',

		/* ShowroomController */
		'order_placed' => 'Order Placed Successfully',

		/* PaymentController */

		// etc

		/// COSTING MESSAGES //

		'labour_charge_not_added' => 'Labour charges not added in the system',
		'certificate_exsist' => ' Certificate(s)  already exists',
		'import_success' => 'Import successfully',
		'qc_status_approved' => 'Product(s) has been accepted successfully',
		'qc_status_rejected' => 'Product(s) has been rejected successfully',
		'IGI_added_success' => 'IGI has been added successfully',
		'request_invoice_success' => 'Requested invoice successfully',
		'return_memo_success' => 'Returned memo successfully',
		'item_exsist' => ' Item(s)  already exists',
		'igied_already' => ' certificate(s) already igied',
		'igi_rejected_success' => 'IGI Rejected Successfully',
		'update_products_success' => 'Product(s) has been Updated successfully',
		'update_products_failure' => 'Product(s) has been not Updated successfully',
		'delete_products_success' => 'Product(s) has been Deleted successfully',
		'delete_products_failure' => 'Product(s) has been not Deleted successfully',
		// COSTING MESSAGES ///

		/* Diamond Inventory Messages */
		'Diamond_Transaction_add_success' => 'Diamond Transaction Add Successfully',
		'Diamond_weight_update_success' => 'Diamond Weight Updated Successfully',
		'Diamond_Transaction_update_success' => 'Diamond Transaction Updated Successfully',
		'Diamond_invoiceattachment_add_success' => 'Diamond invoice attchment added successfully',
		'diamond_issue_added_success' => 'Diamond Issued Successfully',
		'diamond_issue_updated_success' => 'Diamond Updated successfully',
		'Diamond_combination_repeat' => 'Diamond combination repeat',
		'Diamond_date_check' => 'Due date should be grater',
		'Diamond_vendor_exist' => 'Vendor id does not exists in database',
		'Diamond_packet_exist' => 'Packet id does not exists in database',
		'DiamondRaw_Add' => 'Raw Diamond Created successfully ',
		'DiamondRaw_CVD' => 'Raw Diamond CVD Transaction  successfully ',
		'DiamondRaw_Assorted' => 'Raw Diamond Assorted Transaction  successfully ',
		'DiamondRaw_Sizing' => 'Raw Diamond Sizing Transaction  successfully ',
		'Diamond_weight_mismatch' => 'Total weight is mismatch',
		'exceeded_loss_limit' => 'You have Exceeded Loss Limit !',
		'Diamond_Inventory_upload_file' => 'Please upload Excel file',
		'Diamond_Inventory_upload_invalid_file' => 'Please upload a valid xls/xlsx file..!!',
		/* Diamond Inventory Messages */

		/*metal controller*/
		'Metal_add_transaction' => 'Metal transaction added successfully',
		'issue_transaction' => 'Metal issued successfully',
		'metal_weight' => 'You cant issue , because selected metal weight is not available in inventory',
		'metal_cant_issue' => 'You cant issue , because selected metal type is not available in inventory',
		'diamond_cant_issue' => 'You cant issue , because selected Diamond type is not available in inventory',
		/*metal controller*/

		/* Reset Password Link */
		'reset_link_success' => 'we have e-mailed your password reset link !!',
		/* Reset Password Link */

		/*Inventory Messages*/
		'inventory_frncode_already_exist' => 'FRN Code already exist',
		'inventory_new_invoice_created' => 'New invoice created',
		'inventory_bulk_upload_invalid_file' => 'Please upload CSV file',
		'product_image_download_limit' => 'Product limit is upto 500 only for Generate PDF',
		'inventory_status_changed' => 'Inventory status changed successfully',
		'inventory_default_failure_message' => 'Something went wrong! Please try again',
		'inventory_status_not_changed' => 'Something went wrong! Please try again',
		'inventory_status_product_not_selected' => 'Please select product',
		'inventory_generate_approval_confirmation' => 'Are you sure to generate approval?',
		'inventory_cancel_approval_confirmation' => 'Are you sure to cancel approval?',
		'inventory_deliver_approval_confirmation' => 'Are you sure to deliver approval?',
		'inventory_approval_cancellation_success_message' => 'Approval cancelled successfully',
		'inventory_approval_delivery_success_message' => 'Approval delivered successfully',
		'inventory_approval_number_not_generated' => 'Approval number not generated for this Certificate(s): ',
		'inventory_approval_number_not_generated_for_memo' => 'Approval number not generated for this approval',
		'inventory_approval_number_already_generated' => 'Approval number already generated',
		'inventory_approval_number_already_cancelled' => 'Approval number already cancelled',
		'inventory_export_excel_product_not_selected' => 'Please select product',
		'inventory_export_pdf_product_not_selected' => 'Please select checkbox',
		'inventory_generate_memo_product_not_selected' => 'Please select product!',
		'inventory_generate_invoicememo_approval_not_selected' => 'Please select approval memo!',
		'inventory_export_csv_product_not_selected' => 'Are you sure to download csv for all products?',
		'inventory_approval_generated_success_message' => 'Approval generated successfully',
		'inventory_generate_invoicememo_product_not_selected' => 'Please select product!',
		'inventory_generate_invoicememo_customer_not_exist' => 'Customer is not available',
		'invoice_already_generated' => 'Invoice already generated for Certificate(s): ',
		'invoice_number_already_generated' => 'Invoice already generated for this invoice number',
		'invoice_already_generated_for_approval' => 'Invoice already generated for Approval(s): ',
		'return_memo_already_generated_for_approval' => 'Return memo already generated for Approval(s): ',
		'return_memo_already_generated_for_products' => 'Return memo already generated for Certificate(s): ',
		'memo_already_generated' => 'Memo already generated for Certificate(s): ',
		'inventory_quotation_product_not_selected' => 'Plese select product',
		'inventory_quotation_generate_success_message' => 'Quotation generated successfully',
		'inventory_quotation_update_success_message' => 'Quotation updated successfully',
		'inventory_quotation_delete_success_message' => 'Quotation deleted successfully',
		'inventory_quotation_save_failure_message' => 'Something went wrong! Please try again later!',
		'sales_credit_note_generate_confirmation' => 'Are you sure to generate credit note?',
		'inventory_delete_quotation_confirmation' => 'Are you sure to delete quotation?',
		'qrcode_generated' => 'Qrcode generated successfully',
		'qrcode_not_generated' => 'Qrcode not generated',
		'inventory_certificate_added' => 'added successfully',
		'inventory_certificate_not_deleted' => 'Certificate(s) not removed successfully',
		'inventory_certificate_deleted' => 'Certificate(s) removed successfully',
		'inventory_certificate_doesnt_exist' => 'This certificate doesn\'t exist',
		'inventory_certificate_not_found' => 'Certificate not available',
		'inventory_certificate_already_exist' => 'This certificate are already exist',
		'inventory_generate_invoicememo_csv_not_selected' => 'Please upload CSV',
		'inventory_generate_returnmemo_confirmation' => 'Are you sure to generate return memo ?',
		'inventory_memo_generated_success' => 'Memo generated successfully',
		'inventory_memo_generated_failure' => 'Something went wrong! Please try again later!',
		'inventory_product_moved_to_showroom_success' => 'Product moved to inventory successfully',
		'inventory_memo_not_generated' => 'Approval not generated for this Certificate(s): ',
		'invoice_remove_memo_product_confirmation' => 'Are you sure to remove this product?',
		'inventory_return_memo_generated_success' => 'Return memo generated successfully',
		'inventory_product_removed_from_memo' => 'Product removed successfully',
		'invoice_cancellation_success' => 'Invoice canceled successfully!',
		'invoice_updated_successfully' => 'Invoice updated successfully',

		'invoice_cancellation_failure' => 'Something went wrong! Please try again!',
		'invoice_cancellation_already_done' => 'Invoice already cancelled for this Certificate(s): ',
		'invoice_created' => 'New invoice has been created.',
		'invoice_updated' => 'Invoice has been updated.',
		'invoice_address_updated' => 'Invoice address has been updated.',
		'inventory_telephone_already_exist' => 'Contact number already exist',
		'invoice_product_removed' => 'Invoice product has been removed.',
		'invoice_cancelled' => 'Invoice has been cancelled.',
		'inventory_approval_number_already_exist' => 'Approval number already exist',
		'sales_return_already_generated' => 'Sales return already generated for this Certificate(s): ',
		'invoice_cancellation_confirmation' => 'Are you sure to cancel invoice?',
		'exhibition_created_successfully' => 'Exhibition created successfully',
		'exhibition_update_successfully' => 'Exhibition updated successfully',
		'exhibition_product_moved_to_showroom_success' => 'Product moved to showroom successfully',
		///'invoice_number_already_exist'
		'invoice_header_title' => 'DIAMOND MELA JEWELS LTD',
		'invoice_regid' => '2307 PANCHRATNA BUILDING OPERA HOUSE,MUMBAI-400004.',
		'invoice_email' => 'account@diamondmela.com',
		'invoice_telephone' => '18002100888/022-49664966',
		'invoice_web_info' => [
			'text' => 'www.diamondmela.com',
			'url' => 'http://www.diamondmela.com',
		],
		'returnmemo_company_name' => 'DIAMOND MELA JEWELS LTD',
		'returnmemo_address' => '2307 ,23rD FLOOR, PANCHRATNA BLDG,CHARNI ROAD EAST',
		'returnmemo_city' => 'MUMBAI',
		'returnmemo_pincode' => '400004',
		'returnmemo_state' => 'MAHARASHTRA',
		'returnmemo_pan' => 'ARFCO1133A',
		'returnmemo_contactno' => '022 49664966, 49794979',
		'returnmemo_gstin' => '27AAFCD2233A1ZB',
		'returnmemo_hsn_code' => '71131930',
		/*Inventory Messages*/

		/*Customer Messages*/
		'inventory_frncode_already_exist' => 'FRN Code already exist',
		'customer_created_successfully' => 'Customer created successfully',
		'customer_primary_contact_already_exist' => 'Primary contact already exist',
		'customer_secondary_contact_already_exist' => 'Secondary contact already exist',
		'customer_payment_created_successfully' => 'Payment created successfully',
		'customer_created_successfully' => 'Customer created successfully',
		'customer_approval_products_not_available' => 'No approval products available',
		'customer_approval_memo_not_available' => 'No approval memo available',
		'customer_invoice_not_available' => 'No invoices available',
		'costing_not_available' => 'No Costing Data Available',
		'customer_inventory_product_not_available' => 'No inventory product available',
		'customer_address_updated_success' => 'Customer address updated successfully',
		'customer_gstin_updated_success' => 'GSTIN updated successfully',
		'customer_pancard_updated_success' => 'PAN Card updated successfully',
		'customer_personalinfo_updated_success' => 'Personal information updated successfully',
		'customer_pricemarkup_range_error' => 'Please enter a value less than or equal to 100.',
		'customer_pricemarkup_saved_success' => 'Price markup updated successfully',
		'customer_pricemarkup_number_validation_error' => 'Price markup value should be numeric',
		'customer_delete_confirmation_message' => 'Are you sure to delete this customer?',
		'customer_delete_success' => 'Customer deleted successfully',
		'customer_delete_failure' => 'Something went wrong! Please tre again later!',
		/*Customer Messages*/
		/*Quotation Messages*/
		'quotation_set_default_price_message' => 'Set default quotation with DML price',
		'quotation_bulk_rate_file_not_selected' => 'Please upload CSV file',
		'quotation_not_created_for_customer' => 'Quotation not found for this customer',

		/*Quotation Messages */

		/*Showroom Messages*/
		'showroom_status_changed' => 'Order Status Changed Successfully',
		'showroom_status_not_changed' => 'Something went wrong. Order Status Not Changed !',
		'showroom_state_not_selected_for_salesreturn' => 'Please select state',
		'showroom_sales_return_generate_success_message' => 'Sales return generated successfully',
		'showroom_sales_return_generate_failed_message' => 'Something went wrong! Please try again later!',
		'sales_return_dml_address' => '2307, Floor-23 Panchratna, Opera House, Charni Road, Mumbai-400004 Ph: 022-49664999',
		'sales_return_description' => 'Invoice issued under section 31 of the CGST Act, 2017 read with Rule 46 of Central Goods and Services Tax Rules,2017',
		'sales_return_cin' => 'U74999MH2014PLC2603299',
		'sales_return_gstin' => '27AAFCD2233A1ZB',
		'voucher_generated_successfully' => 'Voucher Generated Successfully',
		'Discount_approval' => 'Approval product discount Added successfully.',
		'Discount_deposit' => 'Deposit product discount Added successfully.',
		'Discount_invoice' => 'Invoice discount Added successfully.',

		/*Showroom Messages*/

		/*Diamond*/
		'diamond_combination_are_repeated' => "Diamond Combination Are Repeated",
		'Diamond_weight_more' => "Sorry..!You can't issue due to Diamond weight is more than inventory",
		'Diamond_not_exists' => "Sorry..!Combination of Diamond you don't have in your Invetory",
		'issue_voucher_edit_success' => "Issue Voucher Edited Successfully",
		'issue_voucher_edit_error' => "Issue Voucher edited Could't Be Edited",
		'weight_more' => " Weight is more than Issue",
		'returned_success' => ' Weight Returned successfully',
		'voucherno_generated_sucess' => 'Issue voucher number generated successfully',
		'voucherno_generated_failed' => 'Issue voucher number not generated',
		'voucherno_confirmation' => 'Are you sure to Generate Voucher no?',
		'handover_confirmation' => 'Are you sure to Handover?',
		'handover_sucess' => 'Handover successfully',
		'handover_failed' => 'Handover failed',
		'delete_confirmation' => 'Are you sure to Delete Voucher?',
		'delete_sucess' => 'Voucher Deleted successfully',
		'delete_failed' => 'Vaoucher not Deleted successfully',
		'delete_product_confirmation' => 'Are you sure to Delete Product?',
		/*Diamond*/

		/*Purchase History*/
		'purchase_history_update' => 'Purchase History updated successfully.',
		/*Purchase History*/

		/* Virtual Box Manager */
		'added_vb' => 'Virtual Box Created successfully.',
		"Code_taken" => "Box Code Already Taken",
		"Price_Taken" => "Price Already Taken Between...",
		"Price_Greter_than" => "From Price Already Taken...",
		"Certificate_No_Exist" => "Following Certificate Already Exist",
		"CSV_Data_Not_Found" => "Certificate does not belongs to selected price range",
		"CSV_Record_Added" => "Product Imported",
		"CSV_data_Limit" => "CSV Data is more then your product limit",
		"Product_Not_Fount" => "No products moved yet",
		"Product_Cat_Not_Match" => "Certificate No. Not Match On This Category",
		"VB_Edit" => "Virtual Box Updated successfully.",
		/* Virtual Box Manager - End */
	],
	//COSTING ENUM
	'enum' => [
		'costing_types' => [
			'RD' => "RD",
			'ROUND' => "ROUND",
			'Round' => "Round",
			"platinum" => "platinum",
			'platinum(950)' => "platinum(950)",
			'gold' => "gold",
			'Y' => "Y",
			'YELLOW' => "YELLOW",
			'WHITE' => "WHITE",
			'W' => "W",
			'Rose_Gold' => "Rose Gold",
			'White_Gold' => "White Gold",
			'Yellow_Gold' => "Yellow Gold",
			'ROSE' => "ROSE",
			'PINK' => "PINK",
			'P' => "P",
			'R' => "R",
			'Rose' => "Rose",
			'Pink' => "Pink",
			'Yellow' => "Yellow",
			'White' => "White",
			'Platinum(950)' => "Platinum(950)",
			'THREETONE' => "THREETONE",
			'ThreeTONE' => "ThreeTONE",
			'TwoTONE' => "TwoTONE",
			'TWOTONE' => "TWOTONE",
			'Two_Tone' => "Two Tone",
			'Three_Tone' => "Three Tone",
		],
		'inventory_HSN' => [
			'diamond_HSN' => "7102",
			'gold_HSN' => "7108",
			'platinum_HSN' => "7110",
			'gemstone_HSN' => "71131940",
			'studed_gold_diamond_HSN' => "71131930",
		],
		'description_of_voucher' => [
			'diamond' => 'Cut & Polished Diamonds',
			'gold' => 'Only gold',
			'platinum' => 'Platinum',
		], 'gold_units' => [
			'gold' => 'gms',
		],
		'diamond_shape' => [
			'round' => [
				'round',
			],
			'fancy2' => [
				'taper', 'taper baguette', 'baguette',
			],
			'fancy1' => [],
		],
		'metal_type' => [
			'1' => 'Gold',
			'2' => 'Silver',
			'3' => 'Platinum(950)',
		],
		'transaction_types' => [
			'purchase' => 'Purchase',
			'issue' => 'Issue',
			'purchase_from_vendor' => 'Purchase from Vendor',
			'sell' => 'Sell',
			'misc' => 'Misc',
			'purchase' => 'Purchase',
			'return' => 'Return',
		],
		'customer_view_approval_type' => [
			'oldest_approval' => 'Oldest Approval',
			'newest_approval' => 'Newest Approval',
			'all_approval' => 'No of Approvals',
		],
		'cache_expiry_minutes' => '300',
		'qrcode_url' => 'http://diamondmela.com/index.php/qrinsertproduct/index/scancertificate/certificate_no/',
		'stock_type' => [
			'showroom' => 'Showroom',
			'approval' => 'Approval',
			'pending' => 'Pending',
			'sold' => 'Sold',
		],
	],
	'settings' => [
		'keys' => [
			'diamond_invoice_number' => "DIAMOND_INVOICE_NUMBER",
			'showroom_order_number' => "SHOWROOM_ORDER_NUMBER",
			'pagination' => "PAGINATION_LIMIT",
			'download_image_limit' => "PDF_IMAGE_LIMIT",
			'costing_nearby_amount' => 'COSTING_NEARBY_AMOUNT',
			'sales_return_number' => "SALES_RETURN_NUMBER",
			'return_memo_nub' => "RETURNED_MEMO_NUMBER",
			'quotation_number' => "QUOTATION_NUMBER",
			'approval_number' => "APPROVAL_NUMBER",
			'return_memo_number' => "RETURN_MEMO_NUMBER",
			'diamond_loss' => "DIAMOND_LOSS_TOLERENCE_LIMIT",
			'invoice_limit' => "INVOICE_LIMIT",
			'issue_voucher_prifix' => "ISSUE_VOUCHER_NO_PREFIX",
			'diamond_issue_voucher_prifix' => "DIAMOND_ISSUE_VOUCHER_NO_PREFIX",
			'diamond_voucher_series' => "DIAMOND_VOUCHER_NO_SERIES",
			'gold_voucher_series' => "GOLD_VOUCHER_NO_SERIES",
			'misc_loss_limit' => "MISC_LOSS_LIMIT",
			'discount_invoice_less_25' => 'DISCOUNT_INVOICE_LESS_25K_14K',
			'discount_invoice_25_to_lakhs' => 'DISCOUNT_INVOICE_BETWEEN_25K_TO_100K_14K',
			'discount_invoice_above_lakhs' => 'DISCOUNT_INVOICE_ABOVE_100K_14K',
			'discount_invoice_less_25_18k' => 'DISCOUNT_INVOICE_LESS_25K_18K',
			'discount_invoice_25_100k_18k' => 'DISCOUNT_INVOICE_BETWEEN_25K_TO_100K_18K',
			'discount_invoice_gt_100k_18k' => 'DISCOUNT_INVOICE_ABOVE_100K_18K',
			'invoice_increment_id_prefix' => 'INVOICE_INCREMENT_ID_PREFIX',
			'invoice_increment_id' => 'INVOICE_INCREMENT_ID',
			'Delivery_Challan_No' => 'DELIVERY_CHALLAN_NO',
			'igst_percentage' => 'IGST_PERCENTAGE',
			'sgst_percentage' => 'SGST_PERCENTAGE',
			'cgst_percentage' => 'CGST_PERCENTAGE',
			'qc_approval_voucher_no' => 'QC_APPROVAL_VOUCHER_NO',
			'voucher_number' => 'VOUCHER_NUMBER',
		],
	],
	'labels' => [
		'setting_page' => [
			'diamond_invoice_number' => "DIAMOND INVOICE NUMBER",
			'general_setting' => "General Setting",
			'pagination' => "Default Pagination Limit",
			'download_image_limit' => "PDF Image Limit",
			'showroom' => "Showroom",
			'diamond_page' => "Diamond",
			'order_number' => "Order Number",
			'sales_return_number' => 'Sales Return Number',
			'rawdiamond' => "Raw Diamond",
			'return_memo' => "Return Number",
			'quotation_number' => "Quotation Number",
			'approval_number' => "Approval Number",
			'return_memo_number' => "Return Memo Number",
			'inventory' => "Inventory",
			'issue_voucher_prifix' => "Issue Voucher No Prefix",
			'diamond_issue_voucher_prifix' => "Diamond Issue Voucher No Prefix",
			'diamond_voucher_series' => "Diamond Voucher No Series",
			'gold_voucher_series' => "Gold Voucher No Series",
			'misc_loss_limit' => "Misc Loss Limit",
			'costing' => "Costing",
			'costing_nearby_amount' => "Costing Near by Amount",
			'diamond_loss' => "Diamond Loss",
			'invoice_limit' => "Invoice Limit",
			'cache' => "Cache",
			'cache_types' => "Cache Types",
			'cache_types' => "Cache Types",
			'application_cache' => "Application Cache",
			'config_cache' => "Config Cache",
			'route_cache' => "Route Cache",
			'view_cache' => "View Cache",
			'tmp_var' => "Tmp Var",
			'discount_invoice_less_25' => 'Discount Invoice Less 25k 14k(%)',
			'discount_invoice_25_to_lakhs' => 'Discount Invoice Between 25k to 100k 14k(%)',
			'discount_invoice_above_lakhs' => 'Discount Invoice Above 100k 14k(%)',
			'discount_invoice_less_25_18k' => 'Discount Invoice Less 25k 18k(%)',
			'discount_invoice_25_100k_18k' => 'Discount Invoice between 25k to 100k 18k(%)',
			'discount_invoice_gt_100k_18k' => 'Discount Invoice Above 100k 18k(%)',
			'invoice_increment_id_prefix' => 'Invoice Increment ID Prefix',
			'invoice_increment_id' => 'Invoice Increment ID',
			'Delivery_Challan_No' => 'Delivery Challan No',
			'backup' => 'DB Backup',
			'db_backup' => 'DB Backup',
			'backup_modules' => "Backup Modules",
			'igst_percentage' => "IGST Percentage",
			'sgst_percentage' => "SGST Percentage",
			'cgst_percentage' => "CGST Percentage",
			'qc_approval_voucher_no' => 'Approval Voucher No',
			'voucher_number' => 'Voucher Number',

		],
		'pending' => 'Pending',
		'given_to_vendor' => 'Given to Vendor',
		'in_progress' => 'In Progress',
		'completed' => 'Completed',
	],
	'apiurl' => [
		'local' => [
			'get_metal' => 'http://127.0.0.1/dealermela/index.php/dmlapi/inventory/getmetal/',
			'create_customer' => 'http://127.0.0.1/dealermela/index.php/dmlapi/customers/registercustomerforinventory/',
			'search_customer' => 'http://127.0.0.1/dealermela/index.php/dmlapi/customers/searchcustomer/',
			'get_customer' => 'http://127.0.0.1/dealermela/index.php/dmlapi/customers/getcustomerbyid/',
			'generate_invoice' => 'http://127.0.0.1/dealermela/index.php/dmlapi/inventory/generateinvoice/',
			'generate_seperate_invoice' => 'http://127.0.0.1/dealermela/index.php/dmlapi/inventory/generateseperateinvoice/',
			'generate_memo' => 'http://127.0.0.1/dealermela/index.php/dmlapi/inventory/generatememo/',
			'generate_return_memo' => 'http://127.0.0.1/dealermela/index.php/dmlapi/inventory/generatereturnmemo/',
			'remove_from_order' => 'http://127.0.0.1/dealermela/index.php/dmlapi/inventory/removeproductfromorder/',
			'get_country_list' => 'http://127.0.0.1/dealermela/index.php/dmlapi/customers/getallcountrylist', //'http://127.0.0.1/dealermela/index.php/dmlapi/customers/getallcountrylist',
			'get_state_list' => 'http://127.0.0.1/dealermela/index.php/dmlapi/customers/getallregionlist',
			'remove_memo_product' => 'http://123.108.51.11/index.php/dmlapi/inventory/removememoproduct/',
			'regenerate_memo' => 'http://123.108.51.11/index.php/dmlapi/inventory/regeneratememo',
			'regenerate_invoice' => 'http://123.108.51.11/index.php/dmlapi/inventory/regenerateinvoice',
			'get_country_name' => 'http://127.0.0.1/dealermela/index.php/dmlapi/customers/getcountryname',
			'remove_invoice_product' => 'http://127.0.0.1/dealermela/index.php/dmlapi/inventory/removeinvoiceproduct/',
			'get_in' => 'In',
			'update_customer_address' => 'http://127.0.0.1/dealermela/index.php/dmlapi/customers/updatecustomeraddress/',
			'website_url_for_gst_pan_attachment' => 'http://diamondmela.com/upload_customer_doc.php',
			'update_order_address' => 'http://127.0.0.1/dealermela/index.php/dmlapi/inventory/updateorderaddress/',
			'website_url_for_gst_pan_attachment' => 'http://diamondmela.com/upload_customer_doc.php',
		],
		'live' => [
			'create_customer' => 'http://10.22.40.7/index.php/dmlapi/customers/registercustomerforinventory/',
			'search_customer' => 'http://10.22.40.7/index.php/dmlapi/customers/searchcustomer/',
			'get_customer' => 'http://10.12.40.16/index.php/dmlapi/customers/getcustomerbyid/',
			'generate_invoice' => 'http://10.22.40.7/index.php/dmlapi/inventory/generateinvoice/',
			'generate_seperate_invoice' => 'http://10.22.40.7/index.php/dmlapi/inventory/generateseperateinvoice/',
			'generate_memo' => 'http://10.22.40.7/index.php/dmlapi/inventory/generatememo/',
			'generate_return_memo' => 'http://10.22.40.7/index.php/dmlapi/inventory/generatereturnmemo/',
			'remove_from_order' => 'http://10.22.40.7/index.php/dmlapi/inventory/removeproductfromorder/',
			'get_country_list' => 'http://10.22.40.7/index.php/dmlapi/customers/getallcountrylist',
			'get_state_list' => 'http://10.22.40.7/index.php/dmlapi/customers/getallregionlist',
			'remove_memo_product' => 'http://10.22.40.7/index.php/dmlapi/inventory/removememoproduct/',
			'remove_invoice_product' => 'http://10.22.40.7/index.php/dmlapi/inventory/removeinvoiceproduct/',
			'regenerate_memo' => 'http://10.22.40.7/index.php/dmlapi/inventory/regeneratememo',
			'regenerate_invoice' => 'http://10.22.40.7/index.php/dmlapi/inventory/regenerateinvoice',
			'get_country_name' => 'http://10.22.40.7/index.php/dmlapi/customer/getcountryname',
			'get_in' => ' In',
			'update_customer_address' => 'http://10.22.40.7/index.php/dmlapi/customers/updatecustomeraddress/',
			'website_url_for_gst_pan_attachment' => 'http://diamondmela.com/upload_customer_doc.php',
			'get_metal' => 'http://10.22.40.7/index.php/dmlapi/inventory/getmetal/',
			'update_order_address' => 'http://10.22.40.7/index.php/dmlapi/inventory/updateorderaddress/',
		],
		'test' => [
			'get_metal' => 'http://10.12.40.16/index.php/dmlapi/inventory/getmetal/',
			'create_customer' => 'http://10.12.40.16/index.php/dmlapi/customers/registercustomerforinventory/',
			'search_customer' => 'http://10.12.40.16/index.php/dmlapi/customers/searchcustomer/',
			'get_customer' => 'http://10.12.40.16/index.php/dmlapi/customers/getcustomerbyid/',
			'generate_invoice' => 'http://10.12.40.16/index.php/dmlapi/inventory/generateinvoice/',
			'generate_seperate_invoice' => 'http://10.12.40.16/index.php/dmlapi/inventory/generateseperateinvoice/',
			'generate_memo' => 'http://10.12.40.16/index.php/dmlapi/inventory/generatememo/',
			'generate_return_memo' => 'http://10.12.40.16/index.php/dmlapi/inventory/generatereturnmemo/',
			'remove_from_order' => 'http://10.12.40.16/index.php/dmlapi/inventory/removeproductfromorder/',
			'get_country_list' => 'http://10.12.40.16/index.php/dmlapi/customers/getallcountrylist',
			'get_state_list' => 'http://10.12.40.16/index.php/dmlapi/customers/getallregionlist',
			'remove_memo_product' => 'http://10.12.40.16/index.php/dmlapi/inventory/removememoproduct/',
			'remove_invoice_product' => 'http://10.12.40.16/index.php/dmlapi/inventory/removeinvoiceproduct/',
			'regenerate_memo' => 'http://10.12.40.16/index.php/dmlapi/inventory/regeneratememo',
			'regenerate_invoice' => 'http://10.12.40.16/index.php/dmlapi/inventory/regenerateinvoice',
			'get_country_name' => 'http://10.12.40.16/index.php/dmlapi/customer/getcountryname',
			'get_in' => 'In',
			'update_customer_address' => 'http://10.12.40.16/index.php/dmlapi/customers/updatecustomeraddress/',
			'website_url_for_gst_pan_attachment' => 'http://123.108.51.11/upload_customer_doc.php',
			'update_order_address' => 'http://10.12.40.16/index.php/dmlapi/inventory/updateorderaddress/',
		],
	],

	'local' => [
		'create_user' => 'http://127.0.0.1/dealermela/index.php/dmlapi/customers/registercustomerforsoftware/',
		'qrcode_old_image_url_prefix' => 'http://192.168.1.98/dealertest/skin/frontend/default/default/Qrcode/images/',

	],
	'live' => [
		'create_user' => 'http://10.22.40.7/index.php/dmlapi/customers/registercustomerforsoftware/',
		'qrcode_old_image_url_prefix' => 'http://diamondmela.com/skin/frontend/default/default/Qrcode/images/',
	],
	'test' => [
		'create_user' => 'http://10.12.40.16/index.php/dmlapi/customers/registercustomerforsoftware/',
	],
	'fixIds' => [
		'local' => [
			'customer_entity_varchar_firstname' => '350',
			'customer_entity_varchar_lastname' => '7',
			'quotation_stone_quality_id' => '1240',
			'stone_shape_round' => '36',
			'stone_shape_taper_baguette' => '1596',
			'stone_shape_taper' => '1597',
			'stone_shape_baguette' => '1601',
			'inventory_status_in_id' => '3171',
			'category_ids' => [
				'14',
				'287',
				'6',
				'7',
				'8',
				'9',
				'124',
				'289',
				'290',
				'195',
				'43',
				'293',
				'165',
				'295',
			],
		],
		'live' => [
			'customer_entity_varchar_firstname' => '350',
			'customer_entity_varchar_lastname' => '7',
			'quotation_stone_quality_id' => '1240',
			'stone_shape_round' => '36',
			'stone_shape_taper_baguette' => '1596',
			'stone_shape_taper' => '1597',
			'stone_shape_baguette' => '1601',
			'inventory_status_in_id' => '3209',
			'category_ids' => [
				'14',
				'287',
				'6',
				'7',
				'8',
				'9',
				'124',
				'289',
				'290',
				'195',
				'43',
				'293',
				'165',
				'295',
			],
		],
	],
	'fix_labour_charge' => [
		'ROUND' => '600',
		'FANCY1' => '900',
		'FACNY2' => '900',
	],
	'approval_type' => [
		'long_term' => 'Long Term',
		'short_term' => 'Short Term',
	],
	'deposit_type' => [
		'deposit' => 'Deposit',
		'without_deposit' => 'Without Deposit',
	],
	'sales_return_number' => ['1'],
	'invoice_division_number' => [
		'2' => '2',
		'3' => '3',
		'4' => '4',
	],
	'invoice_division_limit' => '15000',
	'product' => [
		'attribute__id' => '41',
	],
	'product_image_pdf' => [
		'image_options' => [
			'with_image' => 'With Image',
			'without_image' => 'Without Image',
		],
	],
	'vendor_option' => [
		'vendor_name' => "DIAMOND MELA",
	],
	'pdf_logo' => [
		'name' => "Diamond Mela Jewels Ltd",
	],
	'role' => [
		'super_admin' => 'Super Admin',
	],
];